### ISSUE TITLE
/ch shows 0,0,0,0

### ISSUE THREAD

**Issue by maxcamorra** [Testaross/ocoords#1]
hey the command /ch only shows 0.0,0.0,0.0,0.0

**Comment by Testaross** [comment]
i just got this print
489.72082519531,-1002.5120239258,27.832094192505,266.1116027832

**Comment by Testaross** [comment]
i updated to use playerpedid instead of cache.ped now

**Comment by maxcamorra** [comment]
> i updated to use playerpedid instead of cache.ped now

now even /c just shows 0...

**Comment by Testaross** [comment]
Your shit busted I can’t replicate it
